import type { Metadata } from "next";
import { Roboto, Inter } from "next/font/google";
import localfont from "next/font/local";

import "./globals.css";

import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Toaster } from "sonner";
import CompareProductProvider from "@/features/products/compare/compareContext/CompareProductProvider";
import CompareLinkButton from "@/features/products/compare/components/compareLinkButton";
import CartProvider from "@/features/products/cart/cartContext/CartProvider";
import { QueryProvider } from "@/lib/providers/QueryProvider";
import { AuthProvider } from "@/features/auth";
import { SessionProvider } from "next-auth/react";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const bpgWeb002Caps = localfont({
  src: [
    {
      path: "../../public/fonts/bpg-web-002-caps-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/bpg-web-002-caps-webfont.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-bpg-web-002-caps",
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = (await import(`@/messages/${locale}.json`)).default;

  return (
    <html lang={locale}>
      <body
        className={`${inter.variable} ${roboto.variable} ${bpgWeb002Caps.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <QueryProvider>
            <SessionProvider>
              <AuthProvider>
                <Toaster position="top-right" richColors closeButton />

                <CartProvider>
                  <Header />
                  <CompareProductProvider>
                    <>
                      {children}
                      <CompareLinkButton />
                    </>
                  </CompareProductProvider>
                </CartProvider>
                <Footer />
              </AuthProvider>
            </SessionProvider>
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
